import os
import json
import time
from typing import Optional, Dict, Any, List
from playwright.sync_api import sync_playwright, Page, Request as PwRequest, Response as PwResponse

from auditor_core.models.trace_models import (
    WorkflowTrace,
    Stage1CredentialTrace,
    Stage2StorageTrace,
    Stage3CallbackTrace
)

class WorkflowObserver:
    """
    Autonomous Workflow Observer Agent (Stage 1 of the Auditor Framework).
    Uses Playwright browser automation to navigate to upload endpoints,
    simulate file uploads, intercept network requests across all 3 stages,
    and structure the collected evidence into a WorkflowTrace object.
    """

    def __init__(self, base_url: str = "http://127.0.0.1:8000", headless: bool = True, traces_dir: str = "data/traces"):
        self.base_url = base_url.rstrip("/")
        self.headless = headless
        self.traces_dir = traces_dir
        os.makedirs(self.traces_dir, exist_ok=True)

    def _create_temp_test_file(self) -> str:
        """Generates a safe local test payload for controlled auditing."""
        temp_dir = os.path.join("data", "temp_payloads")
        os.makedirs(temp_dir, exist_ok=True)
        file_path = os.path.join(temp_dir, "audit_probe_sample.txt")
        with open(file_path, "w", encoding="utf-8") as f:
            f.write("Controlled test payload generated by AI Workflow Observer for security audit evaluation.")
        return os.path.abspath(file_path)

    def observe_upload(
        self,
        file_path: Optional[str] = None,
        upload_method: str = "PUT",
        auth_token: Optional[str] = None,
        timeout_ms: int = 15000
    ) -> WorkflowTrace:
        """
        Executes a controlled file upload observation on the target web portal.
        Captures all 3 upload workflow stages and stores the evidence.
        """
        if not file_path:
            file_path = self._create_temp_test_file()

        file_name = os.path.basename(file_path)
        file_size = os.path.getsize(file_path)

        trace = WorkflowTrace(
            target_page_url=self.base_url,
            test_file_name=file_name,
            test_file_size=file_size
        )

        captured_requests: List[Dict[str, Any]] = []
        stage1_data: Optional[Stage1CredentialTrace] = None
        stage2_data: Optional[Stage2StorageTrace] = None
        stage3_data: Optional[Stage3CallbackTrace] = None

        with sync_playwright() as p:
            browser = p.chromium.launch(headless=self.headless)
            context = browser.new_context(ignore_https_errors=True)
            page = context.new_page()

            def on_request(request: PwRequest):
                try:
                    post_data = request.post_data
                except Exception:
                    post_data = None

                captured_requests.append({
                    "event": "request",
                    "url": request.url,
                    "method": request.method,
                    "headers": request.headers,
                    "post_data": post_data,
                    "timestamp": time.time()
                })

            def on_response(response: PwResponse):
                nonlocal stage1_data, stage2_data, stage3_data
                req = response.request
                url = response.url
                status = response.status

                try:
                    body_text = response.text()
                except Exception:
                    body_text = None

                captured_requests.append({
                    "event": "response",
                    "url": url,
                    "status": status,
                    "headers": response.headers,
                    "body_preview": body_text[:500] if body_text else None,
                    "timestamp": time.time()
                })

                # --- Match Stage 1: Credential Requesting (/api/get-upload-url) ---
                if "/api/get-upload-url" in url and req.method == "POST":
                    try:
                        resp_json = json.loads(body_text) if body_text else {}
                        req_json = json.loads(req.post_data) if req.post_data else {}
                        
                        stage1_data = Stage1CredentialTrace(
                            endpoint_url=url,
                            method=req.method,
                            request_headers=req.headers,
                            request_body=req_json,
                            status_code=status,
                            upload_type=resp_json.get("upload_type", "PUT"),
                            presigned_url=resp_json.get("url", ""),
                            storage_key=resp_json.get("key", ""),
                            expires_in_seconds=resp_json.get("expires_in_seconds"),
                            acl=resp_json.get("acl"),
                            callback_token=resp_json.get("callback_token"),
                            signed_headers=resp_json.get("headers"),
                            form_fields=resp_json.get("fields")
                        )
                    except Exception as e:
                        print(f"[Observer] Error parsing Stage 1 response: {e}")

                # --- Match Stage 2: Direct Upload to S3/MinIO Storage ---
                elif (":9000" in url or "s3" in url.lower()) and req.method in ["PUT", "POST"] and "/minio/" not in url:
                    stage2_data = Stage2StorageTrace(
                        storage_url=url,
                        method=req.method,
                        status_code=status,
                        request_headers=req.headers,
                        payload_size_bytes=file_size,
                        response_headers=response.headers,
                        response_body=body_text
                    )

                # --- Match Stage 3: Callback Notification (/api/upload-complete) ---
                elif "/api/upload-complete" in url and req.method == "POST":
                    try:
                        resp_json = json.loads(body_text) if body_text else {}
                        req_json = json.loads(req.post_data) if req.post_data else {}

                        stage3_data = Stage3CallbackTrace(
                            callback_url=url,
                            method=req.method,
                            request_headers=req.headers,
                            payload=req_json,
                            status_code=status,
                            response_body=resp_json,
                            is_verified=resp_json.get("record", {}).get("verified", False)
                        )
                    except Exception as e:
                        print(f"[Observer] Error parsing Stage 3 response: {e}")

            page.on("request", on_request)
            page.on("response", on_response)

            try:
                # 1. Navigate to target portal
                print(f"[*] Navigating to {self.base_url}...")
                page.goto(self.base_url, wait_until="domcontentloaded", timeout=timeout_ms)
                page.wait_for_selector("#file-input", state="attached", timeout=timeout_ms)

                # 2. Extract Active Scenario Name
                try:
                    scenario_el = page.query_selector("#active-scenario-tag")
                    if scenario_el:
                        trace.scenario_name = scenario_el.inner_text().strip()
                except Exception:
                    pass

                # 3. Supply test file
                print(f"[*] Supplying test payload: {file_name} ({file_size} bytes)...")
                page.set_input_files("#file-input", file_path)

                # Select upload method
                if upload_method:
                    page.select_option("#upload-method", upload_method)

                # Optional Auth token
                if auth_token:
                    page.fill("#auth-token", auth_token)

                # 4. Trigger Direct Upload
                print(f"[*] Triggering direct upload workflow ({upload_method})...")
                page.click("#btn-upload")

                # 5. Wait for workflow to finish
                page.wait_for_function(
                    """() => {
                        const s1 = document.querySelector('#trace-s1-data');
                        const s2 = document.querySelector('#trace-s2-data');
                        const s3 = document.querySelector('#trace-s3-data');
                        const s1Failed = s1 && s1.classList.contains('error');
                        const s2Failed = s2 && s2.classList.contains('error');
                        const s3Failed = s3 && s3.classList.contains('error');
                        const s3Success = s3 && s3.classList.contains('success');
                        return s1Failed || s2Failed || s3Failed || s3Success;
                    }""",
                    timeout=timeout_ms
                )
                time.sleep(1)
                trace.completed = True

            except Exception as e:
                print(f"[!] Observation encountered exception: {e}")
                trace.completed = False
                trace.error_message = str(e)

            finally:
                context.close()
                browser.close()

        # Consolidate captured traces
        trace.stage1 = stage1_data
        trace.stage2 = stage2_data
        trace.stage3 = stage3_data
        trace.raw_network_events = captured_requests

        # Save structured evidence JSON
        trace_filename = f"trace_{int(trace.timestamp)}_{trace.trace_id[:8]}.json"
        trace_file_path = os.path.join(self.traces_dir, trace_filename)
        with open(trace_file_path, "w", encoding="utf-8") as f:
            f.write(trace.model_dump_json(indent=2))

        print(f"[+] Evidence trace successfully saved to: {trace_file_path}")
        return trace
